author: Igor Pavlov
name: 7-Zip
logo: https://www.7-zip.org/7ziplogo.png
description: 7-Zip是一款拥有极高压缩比的开源压缩软件
category: tools
version: '24.09'
platform: windows
url:
  7z2409-x64.exe: https://www.7-zip.org/a/7z2409-x64.exe
  7z2409.exe: https://www.7-zip.org/a/7z2409.exe
  7z2409-arm64.exe: https://www.7-zip.org/a/7z2409-arm64.exe
homepage: https://www.7-zip.org
script:
  args:
    regex: Download 7-Zip ([\d.]+) \(\d{4}-\d{2}-\d{2}\)
    autoupdate:
      7z${cleanVersion}-x64.exe: https://www.7-zip.org/a/7z${cleanVersion}-x64.exe
      7z${cleanVersion}.exe: https://www.7-zip.org/a/7z${cleanVersion}.exe
      7z${cleanVersion}-arm64.exe: https://www.7-zip.org/a/7z${cleanVersion}-arm64.exe
    url: https://www.7-zip.org
  name: appfork-check-update
