author: MetaCubeX
name: Clash Meta for Android Alpha
logo: https://raw.githubusercontent.com/MetaCubeX/ClashMetaForAndroid/main/app/src/main/ic_launcher-playstore.png
description: A Graphical user interface of [Clash.Meta](https://github.com/MetaCubeX/mihomo)
  for Android.
category: network
platform: android
homepage: https://github.com/MetaCubeX/ClashMetaForAndroid
version: Prerelease-alpha
url:
- https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.3-alpha-arm64-v8a-release.apk
- https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.3-alpha-armeabi-v7a-release.apk
- https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.3-alpha-universal-release.apk
- https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.3-alpha-x86-release.apk
- https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.3-alpha-x86_64-release.apk
script: cmfa-alpha
