author: LM Studio
name: LM Studio
logo: https://avatars.githubusercontent.com/u/133744619?s=200&v=4
description: Discover, download, and run local LLMs.
category: tools
version: 0.3.23-3
platform: windows
script:
  name: appfork-check-update
  args:
    regex: LM-Studio-(?<version>[\d.-]+)-x64\.exe
    autoupdate:
    - https://installers.lmstudio.ai/win32/x64/$version/LM-Studio-$version-x64.exe
    - https://installers.lmstudio.ai/win32/arm64/$version/LM-Studio-$version-arm64.exe
url:
- https://installers.lmstudio.ai/win32/x64/0.3.23-3/LM-Studio-0.3.23-3-x64.exe
- https://installers.lmstudio.ai/win32/arm64/0.3.23-3/LM-Studio-0.3.23-3-arm64.exe
homepage: https://lmstudio.ai
