spring:
  profiles:
    # 指定当前配置文件的 profile
    active: test
  main:
    # 指定当前应用的类型，none 表示不是 web 应用
    web-application-type: none
  threads:
    virtual:
      # 启用虚拟线程
      enabled: true

config:
  # 程序需要同步的软件库目录，也可以通过运行时后面添加参数指定 `--config.repo-path=xxx`
  repo-path: plate
