author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2026-07-16 23:00:00 (3568428000)
platform: other
url:
  Nova Lands [2026-07-16 23:00:00]: https://store.epicgames.com/zh-CN/p/nova-lands-4d1788
  纹身大亨 [2026-07-16 23:00:00]: https://store.epicgames.com/zh-CN/p/tattoo-tycoon-b4352c
homepage: https://store.epicgames.com/zh-CN/free-games
