author: Junlong
name: Gohomo
logo: https://raw.githubusercontent.com/junlongzzz/gohomo/main/logo.png
description: Wrapper for [Mihomo](https://github.com/MetaCubeX/mihomo) written in [Golang](https://go.dev).
category: network
platform: windows
homepage: https://github.com/junlongzzz/gohomo
version: 1.0.0
url:
  - https://github.com/junlongzzz/gohomo/releases/download/v1.0.0/gohomo-windows-amd64-v1.0.0.zip
  - https://github.com/junlongzzz/gohomo/releases/download/v1.0.0/gohomo-windows-arm64-v1.0.0.zip
script:
  args:
    autoupdate:
      - https://github.com/junlongzzz/gohomo/releases/download/v${version}/gohomo-windows-amd64-v${version}.zip
      - https://github.com/junlongzzz/gohomo/releases/download/v${version}/gohomo-windows-arm64-v${version}.zip
  name: appfork-check-update
