name: Sync repository to gitee

on:
  workflow_dispatch:
  repository_dispatch: # 仓库调度事件触发
    types:
      - sync-to-gitee
  push:
    branches:
      - main

# 防止重复执行
concurrency:
  # 任务组名
  group: ${{ github.workflow }}-${{ github.ref }}
  # 取消之前的任务
  cancel-in-progress: true

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/junlongzzz
          dst: gitee/junlongzzz
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: 'user'
          clone_style: 'ssh'
          force_update: true
          static_list: ${{ github.event.repository.name }} # 自动获取当前仓库名
